# Dockerfile.backend

FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY birdle/src/backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
